name: Trigger auto deployment for container-app-perwmvr74pbfu

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-perwmvr74pbfu-AutoDeployTrigger-546ca8c0-6e4d-4e96-bc14-657eb0879f9b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPPERWMVR74PBFU_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPPERWMVR74PBFU_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPPERWMVR74PBFU_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPPERWMVR74PBFU_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPPERWMVR74PBFU_REGISTRY_PASSWORD }}
          containerAppName: container-app-perwmvr74pbfu
          resourceGroup: mytodoappbff2
          imageToBuild: default/container-app-perwmvr74pbfu:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


